/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.DAOUsuario;
import controller.ControllerUsuario;
import java.awt.Toolkit;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelUsuario;

/**
 *
 * @author Usuario
 */
public class ViewUsuario extends javax.swing.JFrame {

    ModelUsuario modelUsuario = new ModelUsuario();
    ControllerUsuario controllerUsuario = new ControllerUsuario();
    List<ModelUsuario> listaUsuario = new ArrayList<>();

    /**
     * Creates new form ViewUsuario
     */
    public ViewUsuario() throws SQLException {
        initComponents();
        setIcon();
        iniciarForm();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jtfNome = new javax.swing.JTextField();
        jtfLogin = new javax.swing.JTextField();
        jPasswordSenha = new javax.swing.JPasswordField();
        btnSalvarUsuario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbTabelaUsuarios = new javax.swing.JTable();
        btnLimparUsuario = new javax.swing.JButton();
        jbnAlterarUsuario = new javax.swing.JButton();
        btnExcluirUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Usuários");

        jLabel1.setText("Código");

        jLabel2.setText("Nome de Usuário");

        jLabel3.setText("Login");

        jLabel4.setText("Senha");

        jtfCodigo.setEditable(false);

        jtfLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfLoginActionPerformed(evt);
            }
        });

        btnSalvarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/salvar.png"))); // NOI18N
        btnSalvarUsuario.setText("Salvar");
        btnSalvarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarUsuarioActionPerformed(evt);
            }
        });

        jtbTabelaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nome", "Login"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbTabelaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbTabelaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbTabelaUsuarios);
        if (jtbTabelaUsuarios.getColumnModel().getColumnCount() > 0) {
            jtbTabelaUsuarios.getColumnModel().getColumn(0).setMinWidth(100);
            jtbTabelaUsuarios.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        btnLimparUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/limpar.png"))); // NOI18N
        btnLimparUsuario.setText("Limpar");
        btnLimparUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparUsuarioActionPerformed(evt);
            }
        });

        jbnAlterarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/alterar.png"))); // NOI18N
        jbnAlterarUsuario.setText("Alterar");
        jbnAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnAlterarUsuarioActionPerformed(evt);
            }
        });

        btnExcluirUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/excluir.png"))); // NOI18N
        btnExcluirUsuario.setText("Excluir");
        btnExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                            .addComponent(jtfNome))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jtfLogin))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPasswordSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLimparUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(jbnAlterarUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluirUsuario)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSalvarUsuario)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimparUsuario)
                    .addComponent(jbnAlterarUsuario)
                    .addComponent(btnExcluirUsuario))
                .addContainerGap())
        );

        jtfNome.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfLoginActionPerformed

    private void btnSalvarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarUsuarioActionPerformed
        modelUsuario = new ModelUsuario();
        modelUsuario.setNome(jtfNome.getText());
        modelUsuario.setLogin(jtfLogin.getText());
        modelUsuario.setSenha(String.valueOf(jPasswordSenha.getPassword()));

        if (jtfLogin.getText() == null || jtfNome.getText() == null || String.valueOf(jPasswordSenha.getPassword()).isEmpty() == true) {
            JOptionPane.showMessageDialog(null, "Não pode haver campos vazios", "Atenção", JOptionPane.INFORMATION_MESSAGE);
        } else {

            try {
                if (controllerUsuario.salvarUsuarioController(modelUsuario)) {
                    JOptionPane.showMessageDialog(null, "Cadastro salvo com sucesso!" + "\nGrave sua senha, pois não poderá ser alterada!", "OK", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao cadastrar dados", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(ViewUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                iniciarForm();
            } catch (SQLException ex) {
                Logger.getLogger(ViewUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }

            limparForm();

            /* Metodo antigo
        
        jtfLogin.setText("");
        jtfNome.setText("");
        jPasswordSenha.setText("");

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        String sql = "select usuarios.id, usuarios.nome, usuarios.login from usuarios";
        DAOUsuario dao = new DAOUsuario();
        ResultSet result = dao.ExecuteSQL(sql);

        try {
            while (result.next()) {
                modelo.addRow(new Object[]{result.getInt("id"), result.getString("nome"), result.getString("login")});
            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro ao listar" + erro);
        }
             */
        }
    }//GEN-LAST:event_btnSalvarUsuarioActionPerformed

    private void btnLimparUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparUsuarioActionPerformed
        limparForm();
    }//GEN-LAST:event_btnLimparUsuarioActionPerformed

    private void jtbTabelaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbTabelaUsuariosMouseClicked
        jtfCodigo.setText(jtbTabelaUsuarios.getValueAt(jtbTabelaUsuarios.getSelectedRow(), 0).toString());
        jtfNome.setText(jtbTabelaUsuarios.getValueAt(jtbTabelaUsuarios.getSelectedRow(), 1).toString());
        jtfLogin.setText(jtbTabelaUsuarios.getValueAt(jtbTabelaUsuarios.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_jtbTabelaUsuariosMouseClicked

    private void btnExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirUsuarioActionPerformed
        int linha = jtbTabelaUsuarios.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(null, "Selecione o cadastro que será deletado.", "Selecione um cadastro", JOptionPane.INFORMATION_MESSAGE);
        } else {

            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Tem certeza de que deseja excluir o cadastro?", "Atenção", dialogButton);
            if (dialogResult == 0) {
                try {
                    if (controllerUsuario.excluirUsuarioController(Integer.parseInt(jtfCodigo.getText()))) {
                        JOptionPane.showMessageDialog(null, "Cadastro deletado com sucesso!", "OK", JOptionPane.INFORMATION_MESSAGE);
                        limparForm();
                        iniciarForm();
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Erro ao deletar dados " + ex, "Erro", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(ViewUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println("Yes option");
            } else {
                System.out.println("desistiu de excluir");
            }
        }
    }//GEN-LAST:event_btnExcluirUsuarioActionPerformed

    private void jbnAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnAlterarUsuarioActionPerformed
        int linha = jtbTabelaUsuarios.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(null, "Selecione o cadastro que será alterado.", "Selecione um cadastro", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Tem certeza de que deseja alterar o cadastro?", "Atenção", dialogButton);
            if (dialogResult == 0) {
                try {
                    if (controllerUsuario.alterarUsuarioController((Integer.parseInt(jtfCodigo.getText())), jtfNome.getText(), jtfLogin.getText())) {
                        JOptionPane.showMessageDialog(null, "Cadastro alterado com sucesso!", "OK", JOptionPane.INFORMATION_MESSAGE);
                        limparForm();
                        iniciarForm();
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Erro ao alterar dados " + ex, "Erro", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(ViewUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println("Yes option");
            } else {
                System.out.println("desistiu de alterar");
            }
        }
    }//GEN-LAST:event_jbnAlterarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ViewUsuario().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ViewUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirUsuario;
    private javax.swing.JButton btnLimparUsuario;
    private javax.swing.JButton btnSalvarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordSenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbnAlterarUsuario;
    private javax.swing.JTable jtbTabelaUsuarios;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfLogin;
    private javax.swing.JTextField jtfNome;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/users.png")));
    }

    //Carrega dados na tabela
    private void iniciarForm() throws SQLException {

        listaUsuario = controllerUsuario.listaUsuario();
        DefaultTableModel modelo = (DefaultTableModel) jtbTabelaUsuarios.getModel();
        modelo.setNumRows(0); //limpa linhas da tabela

        for (ModelUsuario modu : listaUsuario) {
            modelo.addRow(new Object[]{modu.getId(), modu.getNome(), modu.getLogin()});
        }

        /* Método antigo
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        String sql = "select usuarios.id, usuarios.nome, usuarios.login from usuarios";
        DAOUsuario dao = new DAOUsuario();
        ResultSet result = dao.ExecuteSQL(sql);

        try {
            while (result.next()) {
                modelo.addRow(new Object[]{result.getInt("id"), result.getString("nome"), result.getString("login")});
            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro ao listar" + erro);
        }
         */
    }

    private void limparForm() {
        jtfCodigo.setText("");
        jtfNome.setText("");
        jtfLogin.setText("");
        jPasswordSenha.setText("");
    }
}
